In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf

## Part A1

In [ ]:
base = 'http://historical.elections.virginia.gov/elections/search/year_from:1924/year_to:2016/office_id:1/stage:General'
response = requests.get(base)
page = BeautifulSoup(response.text, 'html.parser')

In [ ]:
election_items = page.find_all('tr', class_='election_item general_party')

In [ ]:
df = pd.DataFrame({'year':years, 'election_id':election_ids})
df.to_csv('election_ids.csv', index=False)

### Part A2

#### Make a 'data' folder in the folder you're working in (this is where all CSVs by year will be stored)

In [ ]:
# Read back the CSV for election_ids
# Loop over all rows of the DataFrame
# Extract Year, Election ID (convert to string since Pandas stores it as float)

In [3]:
url_for_csv = 'http://historical.elections.virginia.gov/elections/download/80871/precincts_include:0/'
prefix = 'http://historical.elections.virginia.gov/elections/download/'
suffix = '/precincts_include:0/'
### break it down into a prefix and suffix

In [ ]:
election_id_df = pd.read_csv('election_ids.csv')

for i, row in election_id_df.iterrows():

    election_id = row['election_id']
    year = row['year']
    
    response = requests.get(prefix + str(election_id) + suffix)
    with open('data/' + str(year) + '.csv', 'w') as f:
        f.write(response.text)

In [5]:
prefix

'http://historical.elections.virginia.gov/elections/download/'

In [7]:
suffix

'/precincts_include:0/'

In [16]:
election_id = '80871'
year = 2016
#election_id = row['election_id']

In [12]:
response = requests.get(prefix + str(election_id) + suffix)

In [21]:
#response.text

In [22]:
with open('data/' + str(year) + '.csv', 'w') as f:
    f.write(response.text)
    #f.write("Hello World!")

In [45]:
df = pd.read_csv('data/2016.csv')

In [46]:
df.head(5)

,County/City,Unnamed: 1,Unnamed: 2,Hillary R. Clinton,Donald J. Trump,Gary Johnson,Evan McMullin,Jill Stein,All Others,Total Votes Cast
0,NaN,NaN,NaN,Democratic,Republican,Libertarian,Independent,Green,NaN,NaN
1,Accomack County,NaN,NaN,"6,740","8,583",264,112,66,53,"15,818"
2,Albemarle County,NaN,NaN,"33,345","19,259","2,105","1,059",450,508,"56,726"
3,Alexandria City,NaN,NaN,"57,242","13,285","2,020","1,398",592,"1,233","75,770"
4,Alleghany County,NaN,NaN,"2,166","4,874",164,69,35,17,"7,325"

In [47]:
parties = df.loc[0]

In [48]:
republican_candidate = parties[parties == 'Republican'].index[0]

In [49]:
republican_candidate

'Donald J. Trump'

In [50]:
df.drop(0, inplace=True)

In [51]:
df.head(5)

,County/City,Unnamed: 1,Unnamed: 2,Hillary R. Clinton,Donald J. Trump,Gary Johnson,Evan McMullin,Jill Stein,All Others,Total Votes Cast
1,Accomack County,NaN,NaN,"6,740","8,583",264,112,66,53,"15,818"
2,Albemarle County,NaN,NaN,"33,345","19,259","2,105","1,059",450,508,"56,726"
3,Alexandria City,NaN,NaN,"57,242","13,285","2,020","1,398",592,"1,233","75,770"
4,Alleghany County,NaN,NaN,"2,166","4,874",164,69,35,17,"7,325"
5,Amelia County,NaN,NaN,"2,128","4,708",129,41,11,23,"7,040"

In [75]:
#df['Total Votes Cast']
#df['year'] = year


#df[['County/City',republican_candidate,'Total Votes Cast','year']].rename(columns={republican_candidate: 'Republican'})

#df['County/City'].str.find('(')

county_name = 'Chesterfield County (CD 4))'

In [80]:
county_name[:county_name.find('(')-1]

'Chesterfield County'

In [89]:
df[[republican_candidate,'Total Votes Cast']].groupby(df['County/City']).sum()
#df['Total Votes Cast'].groupby(df['County/City']).sum()

                      Donald J. Trump Total Votes Cast
County/City
Accomack County                 8,583           15,818
Albemarle County               19,259           56,726
Alexandria City                13,285           75,770
Alleghany County                4,874            7,325
Amelia County                   4,708            7,040
Amherst County                  9,719           15,396
Appomattox County               5,715            8,011
Arlington County               20,186          121,356
Augusta County                 26,163           36,343
Bath County                     1,548            2,253
Bedford County                 30,659           42,525
Bland County                    2,573            3,139
Botetourt County               13,375           18,739
Bristol City                    4,892            7,032
Brunswick County                3,046            7,669
Buchanan County                 7,296            9,247
Buckingham County               3,950            7,295
Buena Vista City                1,430            2,407
Campbell County                19,551           27,535
Caroline County                 7,147           14,863
Carroll County                 10,663           13,668
Charles City County             1,476            4,107
Charlotte County                3,479            5,808
Charlottesville City            2,960           22,472
Chesapeake City                54,047          112,705
Chesterfield County            85,045          176,461
Clarke County                   4,661            8,213
Colonial Heights City           5,681            8,457
Covington City                  1,349            2,382
Craig County                    2,140            2,794
...                               ...              ...
Richmond City                  15,581          103,484
Richmond County                 2,213            3,661
Roanoke City                   14,789           39,466
Roanoke County                 31,408           51,489
Rockbridge County               6,680           10,795
Rockingham County              25,990           37,487
Russell County                  9,521           12,246
Salem City                      7,226           12,225
Scott County                    8,247           10,100
Shenandoah County              14,094           20,513
Smyth County                    9,750           12,890
Southampton County              5,035            8,878
Spotsylvania County            34,623           62,562
Stafford County                33,868           65,934
Staunton City                   5,133           11,255
Suffolk City                   18,006           43,240
Surry County                    1,819            4,228
Sussex County                   2,055            5,044
TOTALS                      1,769,443        3,984,631
Tazewell County                15,168           18,566
Virginia Beach City            98,224          203,262
Warren County                  11,773           17,960
Washington County              19,320           25,847
Waynesboro City                 4,801            9,204
Westmoreland County             4,448            8,574
Williamsburg City               1,925            7,626
Winchester City                 4,790           10,667
Wise County                    12,086           15,163
Wythe County                   10,046           13,343
York County                    18,837           34,118

[134 rows x 2 columns]

## Part B1

In [ ]:
# Read back the CSV for election_ids
# Loop over all rows of the DataFrame
# Extract Year (convert to string since Pandas stores it as float)
df = pd.read_csv('data/' + str(year) + '.csv')

# drop first row
df.drop(0, inplace=True)

In [ ]:
# define function to_number(series) to convert column of strings to column of integers
series.str.replace(',','').astype(int)

In [ ]:
# define function to extract_county_city
### look for a parenthesis '(' and work accordingly

In [ ]:
# USe groupby(df['County/City']).sum() to calculate Republican Shares
# Add column storing the year of the election
# Append it to a bigger list of DataFrames

# pd.concat() to concatenate all DataFrames into one
final_df = pd.concat(list_of_dfs)
final_df.to_csv('republican_shares.csv')

## Part B2

In [ ]:
# Read in the Republican Shares CSV file
df = pd.read_csv('republican_shares.csv')

# Set multi-index
df.set_index(['County/City', 'Year'], inplace=True)

In [ ]:
# Unstack at County/City level so that you have series by year
df = df['R_SHARE'].unstack(level='County/City')

time_series_plot = df[['Accomack County', 'Amelia County', 'Amherst County', 'Alleghany County']].plot()

# Useful functions: time_series_plot.set_title()   time_series_plot.set_ylabel()
plt.savefig('republican_shares.png')

## Part B3

In [115]:
#j = requests.get(url, params=params).json()

#url = 'https://api.census.gov/data/2016/acs/acs5/profile?get=DP04_0001E,NAME&for=county:*&in=state:51'

prefix = 'https://api.census.gov/data/2016/acs/acs5/profile?get='
variables = 'DP02_0018PE,DP02_0010PE,DP02_0012PE,NAME'
suffix = '&for=county:*&in=state:51'

print(prefix + variables + suffix)

#print(requests.get(prefix + variables + suffix).json())

json_data = requests.get(prefix + variables + suffix).json()

df_acs =pd.DataFrame(json_data[1:], columns=json_data[0])

https://api.census.gov/data/2016/acs/acs5/profile?get=DP02_0018PE,DP02_0010PE,DP02_0012PE,NAME&for=county:*&in=state:51

In [116]:
df_acs.head(5)

  DP02_0018PE DP02_0010PE DP02_0012PE                        NAME state county
0        43.2        35.3        13.5   Accomack County, Virginia    51    001
1        40.9        35.7        11.3  Albemarle County, Virginia    51    003
2        43.8        36.6        18.5  Alleghany County, Virginia    51    005
3        35.9        23.9         8.7     Amelia County, Virginia    51    007
4        39.9        30.4        12.9    Amherst County, Virginia    51    009

In [106]:
df.columns = ['Var1', 'Var2', 'Var3', 'NAME', 'state', 'county']

df['Name'] = df['Name'][:-10]

,0,1,2,3,4,5
0,DP02_0008PE,DP02_0010PE,DP02_0012PE,NAME,state,county
1,12.8,35.3,13.5,"Accomack County, Virginia",51,001
2,9.0,35.7,11.3,"Albemarle County, Virginia",51,003
3,8.3,36.6,18.5,"Alleghany County, Virginia",51,005
4,14.0,23.9,8.7,"Amelia County, Virginia",51,007

In [ ]:
# Use requests.get() to extract the text data and then .json() to convert to a json
j = requests.get(url, params=params).json()

# Convert to DataFrame
df = pd.DataFrame(j[1:], columns=j[0])

### Rename columns as per your choice

# Store in a CSV file
df.to_csv('acs.csv', index=False)

## Part B4

In [ ]:
# Read in the two CSV files

# Merge the two DataFrames
df = share.merge(acs, on='County/City')

# Make a pairplot using seaborn (import seaborn as sns)
sns.pairplot(df, vars=['''<this should be the columns you renamed in B3>'''var1, var2, var3, 'R_SHARE'])

In [ ]:
# Run an OLS Regression using smf (import statsmodels.formula.api as smf)
res = smf.ols('R_SHARE ~ var1 + var2 + var3 <this should be the columns you renamed in B3>', df).fit()

# Print the summary of the OLS Regression
print(res.summary())

In [ ]:
def extract_county(county_name):
    
    if county_name.find('(') < 0:
        return county_name
    else:
        return county_name[:county_name.find('(')-1]

df['County Name'] = df['County/City'].apply(extract_county)